Use interface types instead of class types + Resolve ID issues
Qminder/javascript-api pull request #309
Opened 2021-08-05 09:36 UTC by boxmein

## Description of the change

This PR converts the data model definitions (eg. Location, Ticket) to interfaces. This means that you don't need to instantiate them and can just pass an object with an expected shape. The API will not instantiate any classes either, so it makes sense to rely on the object's shape not its class.

This PR also resolves the ID issues in using the JS API by making it more convenient to pass objects to endpoints, and pass either string or numeral IDs. (When it doesn't matter, the JS API is converted to use string IDs, and when it does, the code performs the conversion itself to the correct form)

Todos: 

- [ ] Unit tests must be updated
- [ ] Make sure that User#isAdmin() User#isOwner() etc methods were not required in any projects

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactor (Changed implementation, but existing functionality and APIs are not changed)

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ] Changes have been reviewed by at least one other engineer

2021-08-17 09:29 UTC, KaarlisCaune reviewed
For some reason `yarn docs` doesn't work for me, so not sure if that would help, but current /docs still reference stuff like `const line = new Line({ id:...`, which is outdated I guess?

2021-09-08 05:58 UTC, 2ndalpha requested changes
Please resolve conflict

2021-09-08 06:55 UTC, boxmein commented
> Please resolve conflict

✅

2021-09-08 06:58 UTC, 2ndalpha approved these changes

2021-09-08 06:58 UTC, merged