fix(websocket): Make websocket reconnect more reliably
Qminder/javascript-api pull request #518
Opened 2023-04-25 06:29 UTC by KarlMae

## Description of the change

Make websocket reconnect more reliably

## Type of change
- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (Changed implementation, but existing functionality and APIs are not changed)

## Related issues

> Fix #3

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ] Changes have been reviewed by at least one other engineer

2023-04-28 12:46 UTC, KarlMae commented on test/unit/GraphQLSubscriptions.test.ts
> -    afterEach(async () => {
This block was testing the following line:

https://github.com/Qminder/javascript-api/pull/518/files#diff-b696092cf2ea982882e23e816d35f6a093ddf5f9bcee13768906934886fb41c8L304


I think it makes sense to detect connection hang-ups in a singular place and that will be ping-pongs and keepalives (at least for some time) so it made sense to not handle non-user-related hangup in the onclose event

2023-05-02 09:53 UTC, 2ndalpha requested changes

2023-05-02 09:53 UTC, 2ndalpha commented on src/services/GraphQLService.ts
> +    console.info('[Qminder API - 28.04.]: Trying to connect to websocket!');
Remove

2023-05-02 09:53 UTC, 2ndalpha commented on src/services/GraphQLService.ts
> +        `[Qminder API - 28.04.]: Failed fetching temporary API key! Retrying in ${
Update the copy

2023-05-02 09:58 UTC, stdevi commented on src/services/GraphQLService.ts
>    openPendingWebSocket(): void {
@KarlMae I wonder, why `openPendingWebSocket` is an unused method?

2023-05-02 10:01 UTC, stdevi commented on src/services/GraphQLService.ts
> +      if (event.code === CLIENT_SIDE_CLOSE_EVENT) {
I wonder, what if code is 1006?

2023-05-02 11:04 UTC, 2ndalpha approved these changes
🚀

2023-05-02 11:04 UTC, merged