feat: unified logging with timestamp
Qminder/javascript-api pull request #766
Opened 2024-12-18 07:44 UTC by 2ndalpha

## Related issues

## Checklist

- [ ] Code is covered with tests.

2025-01-06 07:55 UTC, KarlMae requested changes
Small ask

2025-01-06 07:55 UTC, KarlMae commented on packages/javascript-api/src/lib/services/graphql/graphql.service.ts
> +  private logger: Logger = new Logger('GraphQL');
I think we can omit the type definition?

2025-01-06 07:55 UTC, KarlMae commented on packages/javascript-api/src/lib/services/temporary-api-key/temporary-api-key.service.ts
> +  private logger: Logger = new Logger('TemporaryKey');
Same here

2025-01-06 08:06 UTC, 2ndalpha commented on packages/javascript-api/src/lib/services/graphql/graphql.service.ts
> +  private logger: Logger = new Logger('GraphQL');
Updated

2025-01-06 08:06 UTC, 2ndalpha commented on packages/javascript-api/src/lib/services/temporary-api-key/temporary-api-key.service.ts
> +  private logger: Logger = new Logger('TemporaryKey');
Updated

2025-01-08 07:51 UTC, KarlMae approved these changes
Nice 🍏

2025-01-08 07:57 UTC, merged