feat(graphql): query verifies the response
Qminder/javascript-api pull request #767
Opened 2024-12-18 09:57 UTC by 2ndalpha

## Related issues

## Checklist

- [ ] Code is covered with tests.

2025-01-06 08:35 UTC, KarlMae requested changes
While testing I converted some services to use the generic and it's so much cleaner, thanks!

I left some improvement ideas.

2025-01-06 08:35 UTC, KarlMae commented on packages/javascript-api/src/lib/services/api-base/api-base.ts
> +    if (!responseJson.data && !responseJson.data) {
I think you are checking the same condition twice?

2025-01-06 08:35 UTC, KarlMae commented on packages/javascript-api/src/lib/services/api-base/api-base.ts
> +      throw new Error(
Should we throw ResponseValidationError?

2025-01-06 08:35 UTC, KarlMae commented on packages/javascript-api/src/lib/services/api-base/api-base.ts
> +    if (graphQLResponse.errors && graphQLResponse.errors.length > 0) {
Maybe check for `graphQLResponse.errors?.length` ?

2025-01-06 08:35 UTC, KarlMae commented on packages/javascript-api/src/lib/services/api-base/api-base.ts
> +    return graphQLResponse.data as T;
IMO the function would read much smoother like this:

```
    let response = await fetch(`https://${this.apiServer}/graphql`, init);
    let responseJson = await response.json();

    if (responseJson.errors?.length) {
      throw this.extractGraphQLError(responseJson);
    }
    
    if (!responseJson.data) {
      throw new Error(`Server response is not valid GraphQL response. Response: ${ JSON.stringify(responseJson) }`);
    }
    
    return responseJson.data as T;
```

It subjectively has an easier to follow structure:

1. Fetch
2. Check for errors
3. Check for data and unwrap it

---

The casting is also not necessary?

```
let graphQLResponse: GraphqlResponse = responseJson;
```

2025-01-06 08:35 UTC, KarlMae commented on packages/javascript-api/src/lib/services/graphql/graphql.service.ts
>      if (!query || query.length === 0) {
I think we can remove this check as well.

Query can not be undefined as it is clearly set on the line above.
Query can also not have length 0 because `gql` DocumentNode can not be empty as tested here:

DOM
```
<button (click)="handleClick()">Test</button>
```

class
```
async handleClick(): Promise<void> {
    await Qminder.GraphQL.query(gql``); 
  }
```

Result

https://github.com/user-attachments/assets/51b8d152-caa2-4b05-beb6-a9c8705bebf1

2025-01-06 08:55 UTC, 2ndalpha commented on packages/javascript-api/src/lib/services/api-base/api-base.ts
> +    return graphQLResponse.data as T;
Casting is still needed but I refactored it a bit

2025-01-08 08:39 UTC, KarlMae approved these changes
Let's go 🚀

2025-01-08 09:16 UTC, merged